// ---- 디자인 토큰: 포인트 컬러는 블루 톤(0D47A1 ~ 2196F3)으로 통일합니다 ----
const accentDark = "#0D47A1"; // 진한 남색 - 강조 텍스트, 버튼, 도넛 상위 구간
const accentMid = "#2196F3"; // 중간 블루 - 링크, 도넛 중위 구간
const accentLight = "#90CAF9"; // 연한 블루 - 도넛 하위 구간
const cardRadius = 20;
const cardShadow = "0 10px 30px rgba(13, 71, 161, 0.09)";
const cardBorder = "1px solid rgba(13, 71, 161, 0.06)";

export const styles = {
  page: {
    // 기본 폰트는 globals.css의 body { font-family: 'Pretendard', ... } 를 그대로 상속합니다.
    // 실제 움직이는 그라데이션 물결은 globals.css의 .page-bg-wave::before 레이어가 담당합니다.
    // (인라인 style로는 keyframe 애니메이션을 못 걸어서 여긴 흰 바탕만 깔아둡니다.)
    background: "#FFFFFF",
    position: "relative",
    color: "#1B2430",
    padding: "32px 28px 56px",
    minHeight: "100%",
  },
  // 관리자 페이지 등 일반 페이지 헤더 (좌: 제목, 우: 액션)
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginBottom: 24,
    flexWrap: "wrap",
    gap: 10,
  },
  eyebrow: { fontSize: 13, color: "#5B6472", marginBottom: 4, fontWeight: 600 },
  title: { fontSize: 26, fontWeight: 800, margin: 0, letterSpacing: "-0.01em", color: "#122A54" },
  titleAccent: { color: "#2549F5" },
  headerRight: { display: "flex", alignItems: "center", gap: 14 },

  // 메인 대시보드 헤더: 3열 그리드(빈 칸 / 헤드카피 / 우측 요소)로 짜서, 우측 요소 폭과
  // 무관하게 헤드카피가 콘텐츠 폭 정중앙에 오도록 합니다.
  dashboardHeaderRow: {
    display: "grid",
    gridTemplateColumns: "1fr auto 1fr",
    alignItems: "center",
    marginBottom: 24,
    padding: "26px 0",
    gap: 10,
  },
  headerSpacer: {},
  headerRightEnd: { display: "flex", alignItems: "center", gap: 14, justifySelf: "end" },
  // 헤드카피(작은 제목 + 큰 제목) 전용 - 지마켓 산스 볼드 + 가운데 정렬
  dashboardEyebrow: {
    fontSize: 14.5,
    color: "#5B6472",
    marginBottom: 6,
    fontWeight: 700,
    fontFamily: "'GmarketSans', 'Pretendard', sans-serif",
    textAlign: "center",
  },
  dashboardTitle: {
    fontSize: 44,
    fontWeight: 700,
    margin: 0,
    letterSpacing: "-0.02em",
    color: "#0F1B2E",
    lineHeight: 1.08,
    fontFamily: "'GmarketSans', 'Pretendard', sans-serif",
    textAlign: "center",
  },
  // 상태 배지: 연한 초록 배경의 알약 모양 칩 + 점 + 문구
  liveBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    fontSize: 12.5,
    fontWeight: 700,
    color: "#1E7A46",
    background: "#E4F6EA",
    border: "1px solid rgba(30, 122, 70, 0.15)",
    borderRadius: 999,
    padding: "7px 14px 7px 11px",
  },
  liveBadgeDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    background: "#2FBE64",
    boxShadow: "0 0 0 3px rgba(47, 190, 100, 0.25)",
    display: "inline-block",
  },
  adminLink: {
    fontSize: 12.5,
    color: accentDark,
    fontWeight: 700,
    textDecoration: "none",
    border: cardBorder,
    borderRadius: 999,
    padding: "7px 14px",
    background: "#FFFFFF",
    boxShadow: "0 4px 14px rgba(13, 71, 161, 0.10)",
  },
  tabRow: {
    display: "flex",
    gap: 4,
    borderBottom: "1px solid rgba(13, 71, 161, 0.12)",
    marginBottom: 28,
  },
  tabButton: {
    background: "none",
    border: "none",
    borderBottom: "2px solid transparent",
    padding: "10px 16px",
    fontSize: 14.5,
    fontWeight: 700,
    marginBottom: -1,
  },

  // ---- 이 주의 홍보기조 배너 ----
  weeklyBanner: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 16,
    background: `linear-gradient(120deg, ${accentDark}, ${accentMid})`,
    color: "#FFFFFF",
    borderRadius: cardRadius,
    padding: "22px 28px",
    marginBottom: 20,
    boxShadow: "0 14px 34px rgba(13, 71, 161, 0.28)",
  },
  weeklyBannerLabel: {
    fontSize: 12.5,
    fontWeight: 700,
    color: "rgba(255,255,255,0.92)",
    background: "rgba(255,255,255,0.18)",
    borderRadius: 999,
    padding: "6px 14px",
    flex: "none",
    whiteSpace: "nowrap",
  },
  weeklyBannerContent: {
    fontSize: 19,
    fontWeight: 800,
    lineHeight: 1.35,
    flex: 1,
    minWidth: 240,
  },

  // ---- 히어로(전국 게첩완료율) + 미니 캘린더: 절반씩 나란히 ----
  heroSplitRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 20,
    marginBottom: 24,
    alignItems: "stretch",
  },
  heroRow: {
    display: "flex",
    alignItems: "center",
    gap: 30,
    background: "#FFFFFF",
    border: cardBorder,
    borderRadius: cardRadius,
    boxShadow: cardShadow,
    padding: "18px 30px",
  },
  heroNumberRow: { display: "flex", alignItems: "baseline", gap: 8 },
  heroNumber: { fontSize: 40, fontWeight: 800, color: accentDark, lineHeight: 1 },
  heroLabel: { fontSize: 17, fontWeight: 700, color: "#334", marginBottom: 8 },
  heroSub: { fontSize: 14.5, color: "#5B6472", marginTop: 10, lineHeight: 1.4 },

  // ---- 미니 캘린더 ----
  calendarCard: {
    background: "#FFFFFF",
    border: cardBorder,
    borderRadius: cardRadius,
    boxShadow: cardShadow,
    padding: "16px 20px",
    display: "flex",
    flexDirection: "column",
    // 옆 카드(히어로)와 stretch로 높이가 맞춰질 때, 안의 그리드를 억지로 늘리는 대신
    // 컴팩트한 내용 블록을 카드 안에서 세로로 가운데 정렬해 남는 여백을 자연스럽게 분산시킵니다.
    justifyContent: "center",
  },
  calendarHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  calendarTitle: { fontSize: 15, fontWeight: 800, color: "#122A54" },
  calendarLegend: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 11,
    color: "#5B6472",
    fontWeight: 600,
  },
  calendarLegendDot: {
    width: 9,
    height: 9,
    borderRadius: "50%",
    background: `linear-gradient(150deg, ${accentDark}, ${accentMid})`,
    display: "inline-block",
  },
  calendarWeekRow: {
    display: "grid",
    gridTemplateColumns: "repeat(7, 1fr)",
    marginBottom: 4,
  },
  calendarWeekday: {
    textAlign: "center",
    fontSize: 11,
    fontWeight: 700,
    padding: "2px 0",
  },
  calendarGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(7, 1fr)",
    gap: 6,
  },
  // calendarDay는 세로로 쌓는 슬롯(칸)입니다: 위쪽엔 고정 크기 배지(calendarDayBadge)로
  // 날짜 숫자를, 지시일 중 memo가 있는 날짜만 그 아래 calendarDayMemo를 추가로 보여줍니다.
  // 예전처럼 aspect-ratio로 칸 높이를 고정해버리면 memo 텍스트가 셀 밖으로 넘치므로,
  // 대신 minHeight만 주고 내용에 맞춰 자연스럽게 늘어나게 합니다 - 같은 주(행)의 다른 칸들은
  // CSS 그리드가 알아서 높이를 맞춰주기 때문에 줄이 깨지거나 겹치지 않습니다.
  calendarDay: {
    minHeight: 50,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 3,
    padding: "1px 2px 4px",
    color: "#3A4356",
  },
  calendarDayBadge: {
    width: 26,
    height: 26,
    flex: "none",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "50%",
    fontSize: 13,
    fontWeight: 600,
  },
  calendarDayTodayBadge: {
    boxShadow: `inset 0 0 0 2px ${accentMid}`,
  },
  calendarDayDirectiveBadge: {
    background: "#EAF3FE",
    color: "#2549F5",
    fontWeight: 700,
  },
  // 지시일 memo 미리보기 - 최대 2줄까지만 보여주고 그 이상은 말줄임표로 잘라서,
  // memo가 길어도 셀 높이가 무한정 늘어나거나 다른 셀과 어긋나지 않도록 막습니다.
  calendarDayMemo: {
    fontSize: 9,
    lineHeight: 1.25,
    fontWeight: 600,
    color: "#2549F5",
    textAlign: "center",
    width: "100%",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
    textOverflow: "ellipsis",
    wordBreak: "break-word",
  },

  splitLayout: {
    display: "grid",
    gridTemplateColumns: "1.4fr 1fr",
    gap: 18,
    alignItems: "start",
  },
  bannerGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: 12,
  },
  regionTile: {
    background: "#FFFFFF",
    border: cardBorder,
    borderRadius: cardRadius,
    boxShadow: cardShadow,
    padding: "14px 14px 12px",
    textAlign: "left",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  regionTileTop: { display: "flex", alignItems: "center", gap: 10 },
  regionName: { fontSize: 13, fontWeight: 700, color: "#3A4356" },
  regionPct: { fontSize: 17, fontWeight: 800 },
  regionMeta: { fontSize: 11, color: "#8A9099" },

  detailPanel: {
    background: "#FFFFFF",
    border: cardBorder,
    borderRadius: cardRadius,
    boxShadow: cardShadow,
    padding: 20,
    maxHeight: 560,
    overflowY: "auto",
  },
  detailHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
    marginBottom: 12,
    paddingBottom: 10,
    borderBottom: "1px solid rgba(13, 71, 161, 0.08)",
  },
  detailTitle: { fontSize: 15.5, fontWeight: 800, color: "#122A54" },
  detailCount: { fontSize: 12.5, color: "#5B6472" },
  committeeList: { display: "flex", flexDirection: "column", gap: 6 },
  committeeRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderLeft: "3px solid",
    background: "#F7F9FE",
    padding: "8px 10px",
    borderRadius: 10,
    fontSize: 13,
  },
  committeeName: { color: "#1B2430" },
  badgeDone: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontSize: 11.5,
    color: "#2549F5",
    fontWeight: 600,
  },
  badgeTodo: {
    fontSize: 11.5,
    color: "#ee015c",
    fontWeight: 700,
  },
  statRow: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: 14,
    marginBottom: 20,
  },
  statCard: {
    background: "#FFFFFF",
    border: cardBorder,
    borderRadius: cardRadius,
    boxShadow: cardShadow,
    padding: 18,
  },
  statIcon: { color: accentDark, marginBottom: 8 },
  statLabel: { fontSize: 12.5, color: "#5B6472", marginBottom: 4 },
  statValue: { fontSize: 22, fontWeight: 800, color: "#122A54" },
  statSub: { fontSize: 11.5, color: "#8A9099", marginTop: 4 },
  panelBlock: {
    background: "#FFFFFF",
    border: cardBorder,
    borderRadius: cardRadius,
    boxShadow: cardShadow,
    padding: 22,
    marginBottom: 20,
  },
  panelHeadRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  panelTitle: { fontSize: 15, fontWeight: 800, color: "#122A54" },
  contentTable: { display: "flex", flexDirection: "column", gap: 8 },
  contentRow: {
    display: "grid",
    gridTemplateColumns: "24px 2fr 1fr 1fr 1fr",
    alignItems: "center",
    gap: 12,
    padding: "10px 8px",
    borderBottom: "1px solid rgba(13, 71, 161, 0.06)",
  },
  contentRank: { fontSize: 14, fontWeight: 700, color: "#8A9099" },
  contentInfo: { display: "flex", flexDirection: "column", gap: 3 },
  contentPlatform: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontSize: 11,
    color: "#5B6472",
    fontWeight: 600,
  },
  contentTitle: { fontSize: 13.5, fontWeight: 600 },
  contentMetric: { textAlign: "right" },
  metricValue: { fontSize: 13.5, fontWeight: 700 },
  metricLabel: { fontSize: 10.5, color: "#8A9099" },
  spreadList: { display: "flex", flexDirection: "column", gap: 4 },
  spreadRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 6px",
    borderBottom: "1px solid rgba(13, 71, 161, 0.06)",
  },
  spreadInfo: { flex: 1 },
  spreadMeta: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontSize: 11.5,
    color: "#8A9099",
    marginTop: 3,
  },
  emptyState: {
    padding: "24px 8px",
    textAlign: "center",
    color: "#8A9099",
    fontSize: 13,
  },
  errorBox: {
    background: "#FBEAE6",
    border: "1px solid #E3B3A6",
    color: "#8A3A26",
    borderRadius: 12,
    padding: "10px 14px",
    fontSize: 13,
    marginBottom: 16,
  },
  // ---- 폼 관련 ----
  formOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(15, 24, 48, 0.45)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    zIndex: 50,
  },
  formCard: {
    background: "#FFFFFF",
    borderRadius: cardRadius,
    boxShadow: "0 20px 50px rgba(13, 71, 161, 0.25)",
    padding: 24,
    width: "100%",
    maxWidth: 420,
    maxHeight: "88vh",
    overflowY: "auto",
  },
  formTitle: { fontSize: 16.5, fontWeight: 800, marginBottom: 4, color: "#122A54" },
  formSub: { fontSize: 12.5, color: "#5B6472", marginBottom: 16 },
  formLabel: { fontSize: 12.5, fontWeight: 600, color: "#5B6472", marginBottom: 6, display: "block" },
  formInput: {
    width: "100%",
    border: "1px solid #D7E0F5",
    borderRadius: 10,
    padding: "9px 11px",
    fontSize: 14,
    marginBottom: 14,
    fontFamily: "inherit",
  },
  formRow: { display: "flex", gap: 10, marginBottom: 14 },
  formButtonRow: { display: "flex", gap: 8, justifyContent: "flex-end", marginTop: 6 },
  btnPrimary: {
    background: `linear-gradient(135deg, ${accentDark}, ${accentMid})`,
    color: "#FFFFFF",
    border: "none",
    borderRadius: 10,
    padding: "9px 16px",
    fontSize: 13.5,
    fontWeight: 700,
    boxShadow: "0 6px 16px rgba(13, 71, 161, 0.28)",
  },
  btnSecondary: {
    background: "#FFFFFF",
    color: "#5B6472",
    border: "1px solid #D7E0F5",
    borderRadius: 10,
    padding: "9px 16px",
    fontSize: 13.5,
    fontWeight: 600,
  },
  btnDanger: {
    background: "#FFFFFF",
    color: "#B8452C",
    border: "1px solid #E3B3A6",
    borderRadius: 10,
    padding: "7px 12px",
    fontSize: 12.5,
    fontWeight: 600,
  },
  btnGhost: {
    background: "#FFFFFF",
    border: "1px solid #D7E0F5",
    borderRadius: 10,
    padding: "7px 12px",
    fontSize: 12.5,
    fontWeight: 700,
    color: accentDark,
  },
  toggleRow: { display: "flex", gap: 8, marginBottom: 14 },
  toggleBtn: {
    flex: 1,
    padding: "9px 0",
    borderRadius: 10,
    border: "1px solid #D7E0F5",
    fontSize: 13.5,
    fontWeight: 600,
    background: "#FFFFFF",
    color: "#5B6472",
  },
};

export const colors = { accentDark, accentMid, accentLight, cardRadius, cardShadow };
