export const styles = {
  page: {
    fontFamily:
      "'Apple SD Gothic Neo', 'Malgun Gothic', -apple-system, sans-serif",
    background: "#F3F4F1",
    color: "#1B2430",
    padding: "28px 24px 48px",
    minHeight: "100%",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginBottom: 20,
    flexWrap: "wrap",
    gap: 10,
  },
  eyebrow: { fontSize: 13, color: "#5B6472", marginBottom: 4 },
  title: { fontSize: 24, fontWeight: 700, margin: 0, letterSpacing: "-0.01em" },
  headerRight: { display: "flex", alignItems: "center", gap: 14 },
  updatedAt: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12.5,
    color: "#5B6472",
  },
  adminLink: {
    fontSize: 12.5,
    color: "#223A5E",
    fontWeight: 600,
    textDecoration: "none",
    border: "1px solid #DEE1DB",
    borderRadius: 6,
    padding: "6px 10px",
    background: "#FFFFFF",
  },
  tabRow: {
    display: "flex",
    gap: 4,
    borderBottom: "1px solid #DEE1DB",
    marginBottom: 24,
  },
  tabButton: {
    background: "none",
    border: "none",
    borderBottom: "2px solid transparent",
    padding: "10px 16px",
    fontSize: 14.5,
    fontWeight: 600,
    marginBottom: -1,
  },
  heroRow: {
    display: "flex",
    alignItems: "baseline",
    gap: 16,
    marginBottom: 20,
    background: "#FFFFFF",
    border: "1px solid #DEE1DB",
    borderRadius: 8,
    padding: "18px 22px",
  },
  heroNumber: { fontSize: 42, fontWeight: 700, color: "#223A5E", lineHeight: 1 },
  heroLabel: { fontSize: 14, fontWeight: 600 },
  heroSub: { fontSize: 12.5, color: "#5B6472", marginTop: 2 },
  splitLayout: {
    display: "grid",
    gridTemplateColumns: "1.4fr 1fr",
    gap: 18,
    alignItems: "start",
  },
  bannerGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: 10,
  },
  regionTile: {
    background: "#FFFFFF",
    border: "1px solid #DEE1DB",
    borderRadius: 8,
    padding: "12px 12px 10px",
    textAlign: "left",
  },
  regionName: { fontSize: 13, fontWeight: 600, color: "#5B6472" },
  regionPct: { fontSize: 22, fontWeight: 700, margin: "2px 0 6px" },
  progressTrack: {
    height: 4,
    background: "#EDEEEA",
    borderRadius: 2,
    overflow: "hidden",
  },
  progressFill: { height: "100%", borderRadius: 2 },
  regionMeta: { fontSize: 11, color: "#8A9099", marginTop: 6 },
  detailPanel: {
    background: "#FFFFFF",
    border: "1px solid #DEE1DB",
    borderRadius: 8,
    padding: 16,
    maxHeight: 560,
    overflowY: "auto",
  },
  detailHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
    marginBottom: 12,
    paddingBottom: 10,
    borderBottom: "1px solid #EDEEEA",
  },
  detailTitle: { fontSize: 15.5, fontWeight: 700 },
  detailCount: { fontSize: 12.5, color: "#5B6472" },
  committeeList: { display: "flex", flexDirection: "column", gap: 6 },
  committeeRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderLeft: "3px solid",
    background: "#FAFAF8",
    padding: "8px 10px",
    borderRadius: 4,
    fontSize: 13,
  },
  committeeName: { color: "#1B2430" },
  badgeDone: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontSize: 11.5,
    color: "#2F7C5C",
    fontWeight: 600,
  },
  badgeTodo: {
    fontSize: 11.5,
    color: "#B8452C",
    fontWeight: 700,
  },
  statRow: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: 12,
    marginBottom: 20,
  },
  statCard: {
    background: "#FFFFFF",
    border: "1px solid #DEE1DB",
    borderRadius: 8,
    padding: 16,
  },
  statIcon: { color: "#223A5E", marginBottom: 8 },
  statLabel: { fontSize: 12.5, color: "#5B6472", marginBottom: 4 },
  statValue: { fontSize: 22, fontWeight: 700 },
  statSub: { fontSize: 11.5, color: "#8A9099", marginTop: 4 },
  panelBlock: {
    background: "#FFFFFF",
    border: "1px solid #DEE1DB",
    borderRadius: 8,
    padding: 18,
    marginBottom: 18,
  },
  panelHeadRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  panelTitle: { fontSize: 15, fontWeight: 700 },
  contentTable: { display: "flex", flexDirection: "column", gap: 8 },
  contentRow: {
    display: "grid",
    gridTemplateColumns: "24px 2fr 1fr 1fr 1fr",
    alignItems: "center",
    gap: 12,
    padding: "10px 8px",
    borderBottom: "1px solid #F0F1ED",
  },
  contentRank: { fontSize: 14, fontWeight: 700, color: "#8A9099" },
  contentInfo: { display: "flex", flexDirection: "column", gap: 3 },
  contentPlatform: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontSize: 11,
    color: "#5B6472",
    fontWeight: 600,
  },
  contentTitle: { fontSize: 13.5, fontWeight: 600 },
  contentMetric: { textAlign: "right" },
  metricValue: { fontSize: 13.5, fontWeight: 700 },
  metricLabel: { fontSize: 10.5, color: "#8A9099" },
  spreadList: { display: "flex", flexDirection: "column", gap: 4 },
  spreadRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 6px",
    borderBottom: "1px solid #F0F1ED",
  },
  spreadInfo: { flex: 1 },
  spreadMeta: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontSize: 11.5,
    color: "#8A9099",
    marginTop: 3,
  },
  emptyState: {
    padding: "24px 8px",
    textAlign: "center",
    color: "#8A9099",
    fontSize: 13,
  },
  errorBox: {
    background: "#FBEAE6",
    border: "1px solid #E3B3A6",
    color: "#8A3A26",
    borderRadius: 6,
    padding: "10px 14px",
    fontSize: 13,
    marginBottom: 16,
  },
  // ---- 폼 관련 ----
  formOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(27,36,48,0.45)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    zIndex: 50,
  },
  formCard: {
    background: "#FFFFFF",
    borderRadius: 10,
    padding: 22,
    width: "100%",
    maxWidth: 420,
    maxHeight: "88vh",
    overflowY: "auto",
  },
  formTitle: { fontSize: 16.5, fontWeight: 700, marginBottom: 4 },
  formSub: { fontSize: 12.5, color: "#5B6472", marginBottom: 16 },
  formLabel: { fontSize: 12.5, fontWeight: 600, color: "#5B6472", marginBottom: 6, display: "block" },
  formInput: {
    width: "100%",
    border: "1px solid #DEE1DB",
    borderRadius: 6,
    padding: "9px 11px",
    fontSize: 14,
    marginBottom: 14,
    fontFamily: "inherit",
  },
  formRow: { display: "flex", gap: 10, marginBottom: 14 },
  formButtonRow: { display: "flex", gap: 8, justifyContent: "flex-end", marginTop: 6 },
  btnPrimary: {
    background: "#223A5E",
    color: "#FFFFFF",
    border: "none",
    borderRadius: 6,
    padding: "9px 16px",
    fontSize: 13.5,
    fontWeight: 600,
  },
  btnSecondary: {
    background: "#FFFFFF",
    color: "#5B6472",
    border: "1px solid #DEE1DB",
    borderRadius: 6,
    padding: "9px 16px",
    fontSize: 13.5,
    fontWeight: 600,
  },
  btnDanger: {
    background: "#FFFFFF",
    color: "#B8452C",
    border: "1px solid #E3B3A6",
    borderRadius: 6,
    padding: "7px 12px",
    fontSize: 12.5,
    fontWeight: 600,
  },
  btnGhost: {
    background: "none",
    border: "1px solid #DEE1DB",
    borderRadius: 6,
    padding: "7px 12px",
    fontSize: 12.5,
    fontWeight: 600,
    color: "#223A5E",
  },
  toggleRow: { display: "flex", gap: 8, marginBottom: 14 },
  toggleBtn: {
    flex: 1,
    padding: "9px 0",
    borderRadius: 6,
    border: "1px solid #DEE1DB",
    fontSize: 13.5,
    fontWeight: 600,
    background: "#FFFFFF",
    color: "#5B6472",
  },
};
