// ---- 디자인 토큰: 포인트 컬러는 블루 톤(0D47A1 ~ 2196F3)으로 통일합니다 ----
const accentDark = "#0D47A1"; // 진한 남색 - 강조 텍스트, 버튼, 도넛 상위 구간
const accentMid = "#2196F3"; // 중간 블루 - 링크, 도넛 중위 구간
const accentLight = "#90CAF9"; // 연한 블루 - 도넛 하위 구간
const cardRadius = 20;
const cardShadow = "0 10px 30px rgba(13, 71, 161, 0.09)";
const cardBorder = "1px solid rgba(13, 71, 161, 0.06)";

export const styles = {
  page: {
    fontFamily:
      "'Apple SD Gothic Neo', 'Malgun Gothic', -apple-system, sans-serif",
    background: "linear-gradient(160deg, #F1EEFB 0%, #EAF0FC 45%, #E1EEFE 100%)",
    backgroundAttachment: "fixed",
    color: "#1B2430",
    padding: "32px 28px 56px",
    minHeight: "100%",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginBottom: 24,
    flexWrap: "wrap",
    gap: 10,
  },
  eyebrow: { fontSize: 13, color: "#5B6472", marginBottom: 4, fontWeight: 600 },
  title: { fontSize: 26, fontWeight: 800, margin: 0, letterSpacing: "-0.01em", color: "#122A54" },
  headerRight: { display: "flex", alignItems: "center", gap: 14 },
  updatedAt: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12.5,
    color: "#5B6472",
  },
  adminLink: {
    fontSize: 12.5,
    color: accentDark,
    fontWeight: 700,
    textDecoration: "none",
    border: cardBorder,
    borderRadius: 999,
    padding: "7px 14px",
    background: "#FFFFFF",
    boxShadow: "0 4px 14px rgba(13, 71, 161, 0.10)",
  },
  tabRow: {
    display: "flex",
    gap: 4,
    borderBottom: "1px solid rgba(13, 71, 161, 0.12)",
    marginBottom: 28,
  },
  tabButton: {
    background: "none",
    border: "none",
    borderBottom: "2px solid transparent",
    padding: "10px 16px",
    fontSize: 14.5,
    fontWeight: 700,
    marginBottom: -1,
  },

  // ---- 히어로(전국 게첩완료율) + 미니 캘린더: 절반씩 나란히 ----
  heroSplitRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 18,
    marginBottom: 20,
    alignItems: "stretch",
  },
  heroRow: {
    display: "flex",
    alignItems: "center",
    gap: 20,
    background: "#FFFFFF",
    border: cardBorder,
    borderRadius: cardRadius,
    boxShadow: cardShadow,
    padding: "24px 26px",
  },
  heroNumberRow: { display: "flex", alignItems: "baseline", gap: 8 },
  heroNumber: { fontSize: 40, fontWeight: 800, color: accentDark, lineHeight: 1 },
  heroLabel: { fontSize: 14, fontWeight: 700, color: "#334", marginBottom: 2 },
  heroSub: { fontSize: 12.5, color: "#5B6472", marginTop: 6 },

  // ---- 미니 캘린더 ----
  calendarCard: {
    background: "#FFFFFF",
    border: cardBorder,
    borderRadius: cardRadius,
    boxShadow: cardShadow,
    padding: "20px 22px",
    display: "flex",
    flexDirection: "column",
  },
  calendarHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  calendarTitle: { fontSize: 14.5, fontWeight: 800, color: "#122A54" },
  calendarLegend: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    fontSize: 11,
    color: "#5B6472",
    fontWeight: 600,
  },
  calendarLegendDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    background: accentDark,
    display: "inline-block",
  },
  calendarWeekRow: {
    display: "grid",
    gridTemplateColumns: "repeat(7, 1fr)",
    marginBottom: 4,
  },
  calendarWeekday: {
    textAlign: "center",
    fontSize: 11,
    fontWeight: 700,
    padding: "4px 0",
  },
  calendarGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(7, 1fr)",
    gap: 4,
    flex: 1,
  },
  calendarDay: {
    aspectRatio: "1 / 1",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 12.5,
    borderRadius: 10,
    color: "#3A4356",
  },
  calendarDayToday: {
    boxShadow: `inset 0 0 0 1.5px ${accentMid}`,
  },
  calendarDayDirective: {
    background: `linear-gradient(150deg, ${accentDark}, ${accentMid})`,
    color: "#FFFFFF",
    fontWeight: 800,
  },

  splitLayout: {
    display: "grid",
    gridTemplateColumns: "1.4fr 1fr",
    gap: 18,
    alignItems: "start",
  },
  bannerGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: 12,
  },
  regionTile: {
    background: "#FFFFFF",
    border: cardBorder,
    borderRadius: cardRadius,
    boxShadow: cardShadow,
    padding: "14px 14px 12px",
    textAlign: "left",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  regionTileTop: { display: "flex", alignItems: "center", gap: 10 },
  regionName: { fontSize: 13, fontWeight: 700, color: "#3A4356" },
  regionPct: { fontSize: 17, fontWeight: 800 },
  regionMeta: { fontSize: 11, color: "#8A9099" },

  detailPanel: {
    background: "#FFFFFF",
    border: cardBorder,
    borderRadius: cardRadius,
    boxShadow: cardShadow,
    padding: 20,
    maxHeight: 560,
    overflowY: "auto",
  },
  detailHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
    marginBottom: 12,
    paddingBottom: 10,
    borderBottom: "1px solid rgba(13, 71, 161, 0.08)",
  },
  detailTitle: { fontSize: 15.5, fontWeight: 800, color: "#122A54" },
  detailCount: { fontSize: 12.5, color: "#5B6472" },
  committeeList: { display: "flex", flexDirection: "column", gap: 6 },
  committeeRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    borderLeft: "3px solid",
    background: "#F7F9FE",
    padding: "8px 10px",
    borderRadius: 10,
    fontSize: 13,
  },
  committeeName: { color: "#1B2430" },
  badgeDone: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontSize: 11.5,
    color: "#2F7C5C",
    fontWeight: 600,
  },
  badgeTodo: {
    fontSize: 11.5,
    color: "#B8452C",
    fontWeight: 700,
  },
  statRow: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: 14,
    marginBottom: 20,
  },
  statCard: {
    background: "#FFFFFF",
    border: cardBorder,
    borderRadius: cardRadius,
    boxShadow: cardShadow,
    padding: 18,
  },
  statIcon: { color: accentDark, marginBottom: 8 },
  statLabel: { fontSize: 12.5, color: "#5B6472", marginBottom: 4 },
  statValue: { fontSize: 22, fontWeight: 800, color: "#122A54" },
  statSub: { fontSize: 11.5, color: "#8A9099", marginTop: 4 },
  panelBlock: {
    background: "#FFFFFF",
    border: cardBorder,
    borderRadius: cardRadius,
    boxShadow: cardShadow,
    padding: 22,
    marginBottom: 20,
  },
  panelHeadRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  panelTitle: { fontSize: 15, fontWeight: 800, color: "#122A54" },
  contentTable: { display: "flex", flexDirection: "column", gap: 8 },
  contentRow: {
    display: "grid",
    gridTemplateColumns: "24px 2fr 1fr 1fr 1fr",
    alignItems: "center",
    gap: 12,
    padding: "10px 8px",
    borderBottom: "1px solid rgba(13, 71, 161, 0.06)",
  },
  contentRank: { fontSize: 14, fontWeight: 700, color: "#8A9099" },
  contentInfo: { display: "flex", flexDirection: "column", gap: 3 },
  contentPlatform: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontSize: 11,
    color: "#5B6472",
    fontWeight: 600,
  },
  contentTitle: { fontSize: 13.5, fontWeight: 600 },
  contentMetric: { textAlign: "right" },
  metricValue: { fontSize: 13.5, fontWeight: 700 },
  metricLabel: { fontSize: 10.5, color: "#8A9099" },
  spreadList: { display: "flex", flexDirection: "column", gap: 4 },
  spreadRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 6px",
    borderBottom: "1px solid rgba(13, 71, 161, 0.06)",
  },
  spreadInfo: { flex: 1 },
  spreadMeta: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontSize: 11.5,
    color: "#8A9099",
    marginTop: 3,
  },
  emptyState: {
    padding: "24px 8px",
    textAlign: "center",
    color: "#8A9099",
    fontSize: 13,
  },
  errorBox: {
    background: "#FBEAE6",
    border: "1px solid #E3B3A6",
    color: "#8A3A26",
    borderRadius: 12,
    padding: "10px 14px",
    fontSize: 13,
    marginBottom: 16,
  },
  // ---- 폼 관련 ----
  formOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(15, 24, 48, 0.45)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    zIndex: 50,
  },
  formCard: {
    background: "#FFFFFF",
    borderRadius: cardRadius,
    boxShadow: "0 20px 50px rgba(13, 71, 161, 0.25)",
    padding: 24,
    width: "100%",
    maxWidth: 420,
    maxHeight: "88vh",
    overflowY: "auto",
  },
  formTitle: { fontSize: 16.5, fontWeight: 800, marginBottom: 4, color: "#122A54" },
  formSub: { fontSize: 12.5, color: "#5B6472", marginBottom: 16 },
  formLabel: { fontSize: 12.5, fontWeight: 600, color: "#5B6472", marginBottom: 6, display: "block" },
  formInput: {
    width: "100%",
    border: "1px solid #D7E0F5",
    borderRadius: 10,
    padding: "9px 11px",
    fontSize: 14,
    marginBottom: 14,
    fontFamily: "inherit",
  },
  formRow: { display: "flex", gap: 10, marginBottom: 14 },
  formButtonRow: { display: "flex", gap: 8, justifyContent: "flex-end", marginTop: 6 },
  btnPrimary: {
    background: `linear-gradient(135deg, ${accentDark}, ${accentMid})`,
    color: "#FFFFFF",
    border: "none",
    borderRadius: 10,
    padding: "9px 16px",
    fontSize: 13.5,
    fontWeight: 700,
    boxShadow: "0 6px 16px rgba(13, 71, 161, 0.28)",
  },
  btnSecondary: {
    background: "#FFFFFF",
    color: "#5B6472",
    border: "1px solid #D7E0F5",
    borderRadius: 10,
    padding: "9px 16px",
    fontSize: 13.5,
    fontWeight: 600,
  },
  btnDanger: {
    background: "#FFFFFF",
    color: "#B8452C",
    border: "1px solid #E3B3A6",
    borderRadius: 10,
    padding: "7px 12px",
    fontSize: 12.5,
    fontWeight: 600,
  },
  btnGhost: {
    background: "#FFFFFF",
    border: "1px solid #D7E0F5",
    borderRadius: 10,
    padding: "7px 12px",
    fontSize: 12.5,
    fontWeight: 700,
    color: accentDark,
  },
  toggleRow: { display: "flex", gap: 8, marginBottom: 14 },
  toggleBtn: {
    flex: 1,
    padding: "9px 0",
    borderRadius: 10,
    border: "1px solid #D7E0F5",
    fontSize: 13.5,
    fontWeight: 600,
    background: "#FFFFFF",
    color: "#5B6472",
  },
};

export const colors = { accentDark, accentMid, accentLight, cardRadius, cardShadow };
